% include('views/partials/script', path='/static/jquery/dist/jquery', minified=True)
% include('views/partials/script', path='/static/bootstrap/dist/js/bootstrap', minified=True)
% include('views/partials/script', path='/static/js/index', minified=True)
% include('views/partials/script', path='/static/js/login', minified=True)
% include('views/partials/script', path='/static/js/material', minified=True)
% include('views/partials/script', path='/static/js/material', minified=False)