% include('views/partials/style', path='/static/bootstrap/dist/css/bootstrap', minified=True)
% include('views/partials/style', path='/static/css/font-awesome', minified=True)
% include('views/partials/style', path='/static/css/font-awesome', minified=False)
% include('views/partials/style', path='/static/css/index', minified=False)
% include('views/partials/style', path='/static/css/style', minified=False)
% include('views/partials/style', path='/static/css/reset', minified=False)
% include('views/partials/style', path='/static/css/material-icons', minified=False)
% include('views/partials/style', path='/static/css/material', minified=False)
